app2/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace app2.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

app2/Controllers/comentariosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using app2;

namespace app2.Controllers
{
    public class comentariosController : Controller
    {
        private SemDBEntities db = new SemDBEntities();

        // GET: comentarios
        public ActionResult Index()
        {
            return View(db.comentario.ToList());
        }

        // GET: comentarios/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            comentario comentario = db.comentario.Find(id);
            if (comentario == null)
            {
                return HttpNotFound();
            }
            return View(comentario);
        }

        // GET: comentarios/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: comentarios/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,nombre,recomendacion")] comentario comentario)
        {
            if (ModelState.IsValid)
            {
                db.comentario.Add(comentario);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(comentario);
        }

        // GET: comentarios/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            comentario comentario = db.comentario.Find(id);
            if (comentario == null)
            {
                return HttpNotFound();
            }
            return View(comentario);
        }

        // POST: comentarios/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,nombre,recomendacion")] comentario comentario)
        {
            if (ModelState.IsValid)
            {
                db.Entry(comentario).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(comentario);
        }

        // GET: comentarios/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            comentario comentario = db.comentario.Find(id);
            if (comentario == null)
            {
                return HttpNotFound();
            }
            return View(comentario);
        }

        // POST: comentarios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            comentario comentario = db.comentario.Find(id);
            db.comentario.Remove(comentario);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

app2/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

app2/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

app2/Views/Home/Index.cshtml
@model app2.comentario
@{
    ViewBag.Title = "Home Page";
}

<div class="container-fluid p-0">
    <section class="resume-section p-3 p-lg-5 d-flex d-column" id="about">
        <div class="my-auto">
            <h1 class="mb-0">
                Juan José
                <span class="text-primary">Lemus Vásquez</span>
            </h1>
            <div class="subheading mb-5">
                10 a. Calle "A" 8-34 zona 2 Jardines de San Jose Villa Nueva · (502) 42221093 ·
                <a href="mailto:name@email.com">jlemus003@gmail.com</a>
            </div>
            <div class="subheading mb-5">
                <span class="text-primary">Carne:</span> 201404412
                <p></p>
                <span class="text-primary">Edad:</span> 22 (25 de Enero 1996)
            </div>
            <p class="mb-5">
                Especialista en el desarrollo de programas y mantenimiento de sistemas con más de 3 meses de experiencia. Conocimientoss
                avanasados en distintos lenguajes de programacion, incluidos Java, C, Python, C#, PHP. Capasitado para trabajar en todas las
                etapas del desarrollo de programas, migraciones y continuous integration con jenkis. Con iniciativa propia, responsabilidad y
                liderazgo.
            </p>
            <ul class="list-inline list-social-icons mb-0">
                <li class="list-inline-item">
                    <a href="https://www.facebook.com/juan.vasquez.336">
                        <span class="fa-stack fa-lg">
                            <i class="fa fa-circle fa-stack-2x"></i>
                            <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                        </span>
                    </a>
                </li>
                <li class="list-inline-item">
                    <a href="https://github.com/ocopulus">
                        <span class="fa-stack fa-lg">
                            <i class="fa fa-circle fa-stack-2x"></i>
                            <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                        </span>
                    </a>
                </li>
            </ul>
        </div>
    </section>
    <section class="resume-section p-3 p-lg-5 d-flex flex-column" id="skills">
        <div class="my-auto">
            <h2 class="mb-5">Habilidades</h2>
            <div class="subheading mb-3">Lenguajes de Programacion &amp; Herramientas</div>
            <ul class="list-inline list-icons">
                <li class="list-inline-item">
                    <i class="devicon-amazonwebservices-original"></i>
                </li>
                <li class="list-inline-item">
                    <i class="devicon-android-plain"></i>
                </li>
                <li class="list-inline-item">
                    <i class="devicon-c-plain"></i>
                </li>
                <li class="list-inline-item">
                    <i class="devicon-bootstrap-plain"></i>
                </li>
                <li class="list-inline-item">
                    <i class="devicon-csharp-plain"></i>
                </li>
                <li class="list-inline-item">
                    <i class="devicon-docker-plain"></i>
                </li>
                <li class="list-inline-item">
                    <i class="devicon-git-plain"></i>
                </li>
                <li class="list-inline-item">
                    <i class="devicon-javascript-plain"></i>
                </li>
                <li class="list-inline-item">
                    <i class="devicon-laravel-plain"></i>
                </li>
                <li class="list-inline-item">
                    <i class="devicon-django-plain"></i>
                </li>
                <li class="list-inline-item">
                    <i class="devicon-mysql-plain"></i>
                </li>
                <li class="list-inline-item">
                    <i class="devicon-nodejs-plain"></i>
                </li>
                <li class="list-inline-item">
                    <i class="devicon-oracle-original"></i>
                </li>
                <li class="list-inline-item">
                    <i class="devicon-php-plain"></i>
                </li>
                <li class="list-inline-item">
                    <i class="devicon-python-plain"></i>
                </li>
                <li class="list-inline-item">
                    <i class="devicon-postgresql-plain"></i>
                </li>
            </ul>
            <div class="subheading mb-3">Habilidades</div>
            <ul class="fa-ul mb-0">
                <li>
                    <i class="fa-li fa fa-check"></i>
                    La capacidad de tomar decisiones
                </li>
                <li>
                    <i class="fa-li fa fa-check"></i>
                    Facilidad para trabajar en equipo
                </li>
                <li>
                    <i class="fa-li fa fa-check"></i>
                    Excelente capacidad de liderazgo
                </li>
                <li>
                    <i class="fa-li fa fa-check"></i>
                    Buena capacidad para adaptarse a los cambios
                </li>
                <li>
                    <i class="fa-li fa fa-check"></i>
                    Manejo de grupos
                </li>
            </ul>
            <iframe width="560" height="315" src="https://www.youtube.com/embed/QPr-ND1UjJk" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
        </div>
    </section>
    <section class="resume-section p-3 p-lg-5 d-flex flex-column" id="experience">
        <div class="my-auto">
            <h2 class="mb-5">Experiencias</h2>
            <div class="resume-item d-flex flex-column flex-md-row mb-5">
                <div class="resume-content mr-auto">
                    <h3 class="mb-0">Verdad Radio</h3>
                    <div class="subheading mb-3">Proyecto Propio</div>
                    <p>Actualmente estoy desarrollado una radio online para una entidad religiosa la cual ya se encuentra fusionando, pero el portal web lo estoy desarrollando actualmente.</p>
                </div>
                <div class="resume-date text-md-right">
                    <span class="text-primary">Enero 2018 - Presente</span>
                </div>
            </div>
            <div class="resume-item d-flex flex-column flex-md-row mb-5">
                <div class="resume-content mr-auto">
                    <h3 class="mb-0">Biblioteca de la Facultad de Ingeniería</h3>
                    <div class="subheading mb-3">Voluntariado</div>
                    <p>Ayude a la depuración de la base de datos de la biblioteca de Ingeniera.</p>
                </div>
                <div class="resume-date text-md-right">
                    <span class="text-primary">Junio 2017 - Noviembre 2017</span>
                </div>
            </div>
            <div class="resume-item d-flex flex-column flex-md-row mb-5">
                <div class="resume-content mr-auto">
                    <h3 class="mb-0">Latin American Resources</h3>
                    <div class="subheading mb-3">Practica Supervisada</div>
                    <p>Realice mis practicas supervisadas en la empresa Latin American Resources, donde obtuve la experiencia de trabajar en el área de contabilidad.</p>
                </div>
                <div class="resume-date text-md-right">
                    <span class="text-primary">Septiembre 2013 - Agosto 2013</span>
                </div>
            </div>
        </div>
    </section>
    <section class="resume-section p-3 p-lg-5 d-flex flex-column" id="education">
        <div class="my-auto">
            <h2 class="mb-5">Estudios</h2>
            <div class="resume-item d-flex flex-column flex-md-row mb-5">
                <div class="resume-content mr-auto">
                    <h3 class="mb-0">Universidad de San Carlos de Guatemala</h3>
                    <div class="subheading mb-3">Ingenieria en Ciencias y Sistemas</div>
                    <div>
                        8 &deg; Semestre
                    </div>
                </div>
                <div class="resume-date text-md-right">
                    <span class="text-primary">Enero 2014 - Presente</span>
                </div>
            </div>
            <div class="resume-item d-flex flex-column flex-md-row">
                <div class="resume-content mr-auto">
                    <h3 class="mb-0">Colegio Cristiano el Olivo 2</h3>
                    <div class="subheading mb-3">Bachillerato en Ciencias y Letras con Orientación en Computación</div>
                </div>
                <div class="resume-date text-md-right">
                    <span class="text-primary">2012 - 2013</span>
                </div>
            </div>
        </div>
    </section>
    <section class="resume-section p-3 p-lg-5 d-flex flex-column" id="awards">
        <div class="my-auto">
            <h2 class="mb-5">Logros</h2>
            <ul class="fa-ul mb-0">
                <li>
                    <i class="fa-li fa fa-trophy text-warning"></i>
                    1<sup>er</sup>
                    Lugar en las Olimpiadas Interuniversitarias 2015 en el área de Tecnología
                </li>
            </ul>
        </div>
    </section>
    <section class="resume-section p-3 p-lg-5 d-flex flex-column" id="interests">
        @using (Html.BeginForm("Create", "comentarios"))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Recomendacion</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.recomendacion, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.recomendacion, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.recomendacion, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        @Html.ActionLink("Recomendaciones", "Index", "comentarios")
                    </div>
                </div>
            </div>
        }
        <section class="resume-section p-3 p-lg-5 d-flex flex-column" id="interests"></section>
</div>
</section>

app2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>My Curriculum Vitae</title>

    <link href="~/Content/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Saira+Extra+Condensed:100,200,300,400,500,600,700,800,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i" rel="stylesheet">
    <link href="~/Content/css/font-awesome.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.rawgit.com/konpa/devicon/df6431e323547add1b4cf45992913f15286456d3/devicon.min.css">
    <link href="~/Content/css/simple-line-icons.css" rel="stylesheet" />
    <link href="~/Content/css/resume.min.css" rel="stylesheet" />
    <!--script defer src="https://use.fontawesome.com/releases/v5.0.12/js/all.js" integrity="sha384-Voup2lBiiyZYkRto2XWqbzxHXwzcm4A5RfdfG6466bu5LqjwwrjXCMBQBLMWh7qR" crossorigin="anonymous"></script-->
</head>
<body id="page-top">
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top" id="sideNav">
        <a class="navbar-brand js-scroll-trigger" href="#page-top">
            <span class="d-block d-lg-none">Start Bootstrap</span>
            <span class="d-none d-lg-block">
                <img class="img-fluid img-profile rounded-circle mx-auto mb-2" src="~/Content/img/me2.jpg" alt="">
            </span>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="#about">Datos Personales</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="#skills">Habilidades</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="#experience">Experiencias</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="#education">Estudios</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="#awards">Logros</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="#interests">Recomendaciones</a>
                </li>
            </ul>
        </div>
    </nav>
    @RenderBody()
    <script src="~/Content/js/jquery.min.js"></script>
    <script src="~/Content/js/bootstrap.bundle.min.js"></script>
    <script src="~/Content/js/jquery.easing.min.js"></script>
    <script src="~/Content/js/resume.min.js"></script>
</body>
</html>

app2/Views/comentarios/Create.cshtml
@model app2.comentario

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>comentario</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.recomendacion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.recomendacion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.recomendacion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

app2/Views/comentarios/Delete.cshtml
@model app2.comentario

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>comentario</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.recomendacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.recomendacion)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

app2/Views/comentarios/Details.cshtml
@model app2.comentario

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>comentario</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.recomendacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.recomendacion)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

app2/Views/comentarios/Edit.cshtml
@model app2.comentario

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>comentario</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.recomendacion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.recomendacion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.recomendacion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

app2/Views/comentarios/Index.cshtml
@model IEnumerable<app2.comentario>

@{
    ViewBag.Title = "Index";
}
<section class="resume-section p-3 p-lg-5 d-flex flex-column">
    <h2>Recomendaciones</h2>

    <table class="table">
        <tr>
            <th scope="col">
                @Html.DisplayNameFor(model => model.nombre)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.recomendacion)
            </th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td scope="row">
                    @Html.DisplayFor(modelItem => item.nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.recomendacion)
                </td>
            </tr>
        }

    </table>
    @Html.ActionLink("Regresar", "Index", "Home")
</section>